### ISSUE TITLE
CI/CD Pipeline Deployment

### ISSUE THREAD

**Issue by dotnetspec** [brian-watkins/elm-spec#73]
I appreciate this may not be something that you can assist with if you have not been using a pipeline for your own deployments. However, if you have, then, hopefully, this may be relatively easy to resolve.

I get the following error attempting to run the integration tests in my pipeline:

![SP - elm-spec pipeline error - Screenshot from 2024-03-09 10-15-40](https://github.com/brian-watkins/elm-spec/assets/27340988/0a1cd7fb-ec2b-41e3-8f96-265e658b2838)

This is my gitlab-ci.yml used to configure the pipeline:

```

#Jobs are defined in the .gitlab-ci.yml file and assigned to available runners.

stages:
  - test
  - integration_test
  - deploy
  
test:
  stage: test
  script:
    - apt-get update -qy # Update package list (for Debian/Ubuntu-based runners)
    - apt-get install -y nodejs npm # Install Node.js and npm
    - npm install -g elm # Install Elm
    - elm make src/Main.elm --output=js/elm.js --optimize # Compile Elm to JavaScript
    - npm install -g elm-test # Install Elm test
    - elm-test 'src/**/Tests/Test*.elm'


  
integration_test:
  stage: integration_test
  script:
    - apt-get update -qy 
    - apt-get install -y nodejs npm 
    - npm install elm@latest-0.19.1 
    - export PATH=./node_modules/.bin:$PATH
    - elm --version
    - elm make src/Main.elm --output=js/elm.js --optimize 
    - npm install -g elm-spec
     # I have also tried just 'elm-spec' as the command here:
    - npx elm-spec --specRoot ./ 
   
  

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --update lftp
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)  # Start SSH agent
  
    - lftp -u "$FTP_USERNAME,$FTP_PASSWORD" "$FTP_SERVER:21098" mirror ./js /home/squastgr/public_html/apps/SP-Schedule/public_html/js
    
  only:
    - master
  dependencies:
    - test
    - integration_test
```
    
The runner I use in Gitlab is :
    
```
    Runner:
#12270852 (Jhc_Jxvh8) 3-green.saas-linux-small-amd64.runners-manager.gitlab.com/default
```
Removing the integration_test stage results in a 'pipeline successful', so I know the other parts of the config are working.

Whilst I realize this issue is not directly related to the module itself, currently, being unable to use elm-spec in the deployment pipeline limits it's usefulness in the project as a whole and reduces the efficiency of the overall development process.

Thanks again for your help if possible  ...
